### ISSUE TITLE
low/high budget

### ISSUE THREAD

**Issue by wooozihui** [val-iisc/DAJAT#1]
Is the 2-step ACAT (base) corresponding to the low budget? （train_budget is not in the training script of ACAT and the default setting is "high" ）
`python train_DAJAT.py --use_defaults ['NONE','CIFAR10_RN18', 'CIFAR10_WRN','CIFAR100_WRN', 'CIFAR100_RN18']  --num_autos 0 --epochs 110 --beta`
And in the high budget code, 
```
elif args.train_budget=='high':
            if epoch<=50:
                step_size = varepsilon
                iters_attack = 2
            if epoch<=100:
                step_size = 2*varepsilon/3
                iters_attack = 3
            if epoch<=150:
                step_size = varepsilon/2
                iters_attack = 4
            if epoch<=200:
                step_size = varepsilon/2
                iters_attack = 5
```
it seems finally only the choice of "epoch <= 200" works?

**Comment by samyakjain0112** [comment]
Hi Wu,
Sorry for the late reply. We missed your comment. Yes, the 2-step ACAT (base) corresponds to the low budget. To run for ACAT you will need to pass an additional arg --train_budget low. We missed including this in the readme. Thanks for pointing this out. Please let us know if you have any other concerns.

Thanks,
Samyak
